when_modified:
  autoapply: true
cost_estimation:
  enabled: true
hooks:
  all:
    pre:
      - type: oidc
        provider: aws
        role_arn: "arn:aws:iam::026090549866:role/terrateam"
workflows:
  - tag_query: ""
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      - type: apply